// <auto-generated />
using System;
using Email.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Email.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210064933_AddInboundEmailSupport")]
    partial class AddInboundEmailSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Email.Server.Models.ApiKeys", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("IX_ApiKeys_Domain");

                    b.HasIndex("KeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("UX_ApiKeys_Prefix");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ApiKeys_Tenant");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.BillingPlans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("AllowsOverage")
                        .HasColumnType("bit");

                    b.Property<int>("AnalyticsRetentionDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasDedicatedIp")
                        .HasColumnType("bit");

                    b.Property<int>("IncludedEmails")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxApiKeys")
                        .HasColumnType("int");

                    b.Property<int>("MaxDomains")
                        .HasColumnType("int");

                    b.Property<int>("MaxTeamMembers")
                        .HasColumnType("int");

                    b.Property<int>("MaxTemplates")
                        .HasColumnType("int");

                    b.Property<int>("MaxWebhooks")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyPriceCents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OverageRateCentsPer1K")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StripeMeteredPriceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripePaymentLinkUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeProductId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupportLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_BillingPlans_Name");

                    b.HasIndex("StripePriceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BillingPlans_StripePriceId");

                    b.ToTable("BillingPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AllowsOverage = true,
                            AnalyticsRetentionDays = 7,
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perfect for small projects and startups",
                            DisplayName = "Starter",
                            HasDedicatedIp = false,
                            IncludedEmails = 25000,
                            IsActive = true,
                            MaxApiKeys = 2,
                            MaxDomains = 1,
                            MaxTeamMembers = 1,
                            MaxTemplates = 10,
                            MaxWebhooks = 2,
                            MonthlyPriceCents = 900,
                            Name = "starter",
                            OverageRateCentsPer1K = 40,
                            SortOrder = 1,
                            StripePriceId = "price_starter",
                            StripeProductId = "prod_starter",
                            SupportLevel = "Email",
                            UpdatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AllowsOverage = true,
                            AnalyticsRetentionDays = 30,
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "For growing businesses with higher volume",
                            DisplayName = "Growth",
                            HasDedicatedIp = false,
                            IncludedEmails = 100000,
                            IsActive = true,
                            MaxApiKeys = 10,
                            MaxDomains = 5,
                            MaxTeamMembers = 5,
                            MaxTemplates = 50,
                            MaxWebhooks = 5,
                            MonthlyPriceCents = 2900,
                            Name = "growth",
                            OverageRateCentsPer1K = 30,
                            SortOrder = 2,
                            StripePriceId = "price_growth",
                            StripeProductId = "prod_growth",
                            SupportLevel = "Priority",
                            UpdatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AllowsOverage = true,
                            AnalyticsRetentionDays = 90,
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "For large organizations with custom needs",
                            DisplayName = "Enterprise",
                            HasDedicatedIp = true,
                            IncludedEmails = 500000,
                            IsActive = true,
                            MaxApiKeys = 50,
                            MaxDomains = 999,
                            MaxTeamMembers = 20,
                            MaxTemplates = 200,
                            MaxWebhooks = 20,
                            MonthlyPriceCents = 9900,
                            Name = "enterprise",
                            OverageRateCentsPer1K = 20,
                            SortOrder = 3,
                            StripePriceId = "price_enterprise",
                            StripeProductId = "prod_enterprise",
                            SupportLevel = "24/7",
                            UpdatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Email.Server.Models.ConfigSets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ConfigSetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SesRegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SesRegionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigSets_Scope");

                    b.ToTable("ConfigSets", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.ContactSubmissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RepliedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_ContactSubmissions_Created");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_ContactSubmissions_Email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ContactSubmissions_Status");

                    b.ToTable("ContactSubmissions", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.DomainDnsRecords", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "RecordType", "Host")
                        .IsUnique()
                        .HasDatabaseName("UQ_DomainDnsRecords");

                    b.ToTable("DomainDnsRecords", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.Domains", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DkimMode")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DkimStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdentityArn")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("InboundEnabled")
                        .HasColumnType("bit");

                    b.Property<byte>("InboundStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MailFromStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("MailFromSubdomain")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("VerificationStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("TenantId", "Region", "Domain")
                        .IsUnique()
                        .HasDatabaseName("UQ_Domains_TenantRegion");

                    b.HasIndex("TenantId", "VerificationStatus", "DkimStatus")
                        .HasDatabaseName("IX_Domains_Tenant_Status");

                    b.ToTable("Domains", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.InboundMessages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SesMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("nvarchar(998)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("IX_InboundMessages_DomainId");

                    b.HasIndex("Region");

                    b.HasIndex("TenantId", "ReceivedAtUtc")
                        .HasDatabaseName("IX_InboundMessages_Tenant_Time");

                    b.ToTable("InboundMessages", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.Invoices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AmountDueCents")
                        .HasColumnType("int");

                    b.Property<int>("AmountPaidCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostedInvoiceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvoicePdfUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubtotalCents")
                        .HasColumnType("int");

                    b.Property<int>("TaxCents")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalCents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Invoices_StripeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Invoices_Tenant");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.MessageAttachments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ContentId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsInline")
                        .HasColumnType("bit");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("IX_MessageAttachments_Message");

                    b.ToTable("MessageAttachments", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.MessageEvents", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipient")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("Region");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("IX_MessageEvents_Tenant_Time");

                    b.ToTable("MessageEvents", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.MessageRecipients", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("DeliveryStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SesDeliveryId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStatus")
                        .HasDatabaseName("IX_MessageRecipients_Status");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("IX_MessageRecipients_Message");

                    b.ToTable("MessageRecipients", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.MessageTags", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MessageId", "Name");

                    b.ToTable("MessageTags", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.Messages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("ConfigSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FromName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SesMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("nvarchar(998)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextBody")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigSetId");

                    b.HasIndex("Region");

                    b.HasIndex("SesMessageId")
                        .HasDatabaseName("IX_Messages_SesMessageId");

                    b.HasIndex("TenantId", "RequestedAtUtc")
                        .HasDatabaseName("IX_Messages_Tenant_Time");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.RegionsCatalog", b =>
                {
                    b.Property<string>("Region")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DefaultForNewTenants")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ReceiveSupported")
                        .HasColumnType("bit");

                    b.Property<bool>("SendSupported")
                        .HasColumnType("bit");

                    b.HasKey("Region");

                    b.ToTable("RegionsCatalog", (string)null);

                    b.HasData(
                        new
                        {
                            Region = "us-east-1",
                            CreatedAtUtc = new DateTime(2025, 12, 10, 6, 49, 32, 283, DateTimeKind.Utc).AddTicks(924),
                            DefaultForNewTenants = false,
                            DisplayName = "US East (N. Virginia)",
                            ReceiveSupported = true,
                            SendSupported = true
                        },
                        new
                        {
                            Region = "us-west-2",
                            CreatedAtUtc = new DateTime(2025, 12, 10, 6, 49, 32, 283, DateTimeKind.Utc).AddTicks(4212),
                            DefaultForNewTenants = true,
                            DisplayName = "US West (Oregon)",
                            ReceiveSupported = true,
                            SendSupported = true
                        },
                        new
                        {
                            Region = "eu-west-1",
                            CreatedAtUtc = new DateTime(2025, 12, 10, 6, 49, 32, 283, DateTimeKind.Utc).AddTicks(4216),
                            DefaultForNewTenants = false,
                            DisplayName = "EU (Ireland)",
                            ReceiveSupported = true,
                            SendSupported = true
                        },
                        new
                        {
                            Region = "ap-southeast-2",
                            CreatedAtUtc = new DateTime(2025, 12, 10, 6, 49, 32, 283, DateTimeKind.Utc).AddTicks(4218),
                            DefaultForNewTenants = false,
                            DisplayName = "APAC (Sydney)",
                            ReceiveSupported = true,
                            SendSupported = true
                        });
                });

            modelBuilder.Entity("Email.Server.Models.Senders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Senders");

                    b.ToTable("Senders", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.SesRegions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AwsSesTenantArn")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("AwsSesTenantId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AwsSesTenantName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventBusArn")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("LastStatusCheckUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProvisioningErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("ProvisioningStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SendingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SesTenantCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("TenantId", "Region")
                        .IsUnique()
                        .HasDatabaseName("UQ_SesRegions_TenantRegion");

                    b.ToTable("SesRegions", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.StripeCustomers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultPaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasDatabaseName("UQ_StripeCustomers_StripeId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_StripeCustomers_Tenant");

                    b.ToTable("StripeCustomers", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.StripeWebhookEvents", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ProcessedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("IX_StripeWebhookEvents_Received");

                    b.HasIndex("Processed", "ReceivedAtUtc")
                        .HasDatabaseName("IX_StripeWebhookEvents_Pending");

                    b.ToTable("StripeWebhookEvents", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.Suppressions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_Suppressions_Tenant_Email");

                    b.HasIndex("TenantId", "Region", "Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Suppressions")
                        .HasFilter("[Region] IS NOT NULL");

                    b.ToTable("Suppressions", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.Templates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("nvarchar(998)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("UQ_Templates");

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.TenantInvitations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcceptedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvitationToken")
                        .IsUnique()
                        .HasDatabaseName("UQ_TenantInvitations_Token");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_TenantInvitations_TenantStatus");

                    b.HasIndex("TenantId", "InviteeEmail", "Status")
                        .HasDatabaseName("IX_TenantInvitations_TenantEmailStatus");

                    b.ToTable("TenantInvitations", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.TenantMembers", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("UserEmail")
                        .HasDatabaseName("IX_TenantMembers_Email");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TenantMembers_User");

                    b.ToTable("TenantMembers", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.TenantSubscriptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("BillingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TrialEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrialStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BillingPlanId");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TenantSubscriptions_StripeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_TenantSubscriptions_Tenant");

                    b.ToTable("TenantSubscriptions", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.Tenants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GracePeriodEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBillingEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInGracePeriod")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SendingDisabledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SendingDisabledReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.UsagePeriods", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmailsSent")
                        .HasColumnType("bigint");

                    b.Property<long>("IncludedEmailsLimit")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastStripeReportUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("OverageEmails")
                        .HasColumnType("bigint");

                    b.Property<long>("OverageReportedToStripe")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_UsagePeriods_Subscription");

                    b.HasIndex("TenantId", "PeriodStart")
                        .HasDatabaseName("IX_UsagePeriods_Tenant_Period");

                    b.ToTable("UsagePeriods", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.WebhookDeliveries", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("WebhookEndpointsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("WebhookEndpointsId");

                    b.HasIndex("EndpointId", "Status")
                        .HasDatabaseName("IX_WebhookDeliveries_Endpoint_Status");

                    b.ToTable("WebhookDeliveries", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.WebhookEndpoints", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EventTypes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Secret")
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("WebhookEndpoints", (string)null);
                });

            modelBuilder.Entity("Email.Server.Models.ApiKeys", b =>
                {
                    b.HasOne("Email.Server.Models.Domains", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.ConfigSets", b =>
                {
                    b.HasOne("Email.Server.Models.SesRegions", "SesRegion")
                        .WithMany()
                        .HasForeignKey("SesRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesRegion");
                });

            modelBuilder.Entity("Email.Server.Models.DomainDnsRecords", b =>
                {
                    b.HasOne("Email.Server.Models.Domains", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Email.Server.Models.Domains", b =>
                {
                    b.HasOne("Email.Server.Models.RegionsCatalog", "RegionCatalog")
                        .WithMany()
                        .HasForeignKey("Region")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionCatalog");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.InboundMessages", b =>
                {
                    b.HasOne("Email.Server.Models.Domains", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Email.Server.Models.RegionsCatalog", "RegionCatalog")
                        .WithMany()
                        .HasForeignKey("Region")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("RegionCatalog");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.Invoices", b =>
                {
                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.MessageAttachments", b =>
                {
                    b.HasOne("Email.Server.Models.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Email.Server.Models.MessageEvents", b =>
                {
                    b.HasOne("Email.Server.Models.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Email.Server.Models.RegionsCatalog", "RegionCatalog")
                        .WithMany()
                        .HasForeignKey("Region")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("RegionCatalog");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.MessageRecipients", b =>
                {
                    b.HasOne("Email.Server.Models.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Email.Server.Models.MessageTags", b =>
                {
                    b.HasOne("Email.Server.Models.Messages", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Email.Server.Models.Messages", b =>
                {
                    b.HasOne("Email.Server.Models.ConfigSets", "ConfigSet")
                        .WithMany()
                        .HasForeignKey("ConfigSetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Email.Server.Models.RegionsCatalog", "RegionCatalog")
                        .WithMany()
                        .HasForeignKey("Region")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConfigSet");

                    b.Navigation("RegionCatalog");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.Senders", b =>
                {
                    b.HasOne("Email.Server.Models.Domains", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Email.Server.Models.SesRegions", b =>
                {
                    b.HasOne("Email.Server.Models.RegionsCatalog", "RegionCatalog")
                        .WithMany()
                        .HasForeignKey("Region")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionCatalog");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.StripeCustomers", b =>
                {
                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.Suppressions", b =>
                {
                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.Templates", b =>
                {
                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.TenantInvitations", b =>
                {
                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.TenantMembers", b =>
                {
                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.TenantSubscriptions", b =>
                {
                    b.HasOne("Email.Server.Models.BillingPlans", "BillingPlan")
                        .WithMany()
                        .HasForeignKey("BillingPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingPlan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.UsagePeriods", b =>
                {
                    b.HasOne("Email.Server.Models.TenantSubscriptions", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.WebhookDeliveries", b =>
                {
                    b.HasOne("Email.Server.Models.WebhookEndpoints", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.MessageEvents", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Email.Server.Models.WebhookEndpoints", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("WebhookEndpointsId");

                    b.Navigation("Endpoint");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Email.Server.Models.WebhookEndpoints", b =>
                {
                    b.HasOne("Email.Server.Models.Tenants", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Email.Server.Models.WebhookEndpoints", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
